"""initial schema

Revision ID: d7fb9e878f3f
Revises:
Create Date: 2026-07-15 09:10:21.881335

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d7fb9e878f3f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
